# main menu
[[main]]
  name        = "About Us"
  weight      = 10
  identifier  = "about"
  url         = "/about/"

[[main]]
  name        = "Distinguished Alumni"
  weight      = 20
  identifier  = "distinguished-alumni"
  url         = "/distinguished-alumni/"

[[main]]
  name        = "Scholarships"
  weight      = 25
  identifier  = "scholarships"
  url         = "/scholarships/"

[[main]]
  name        = "News"
  weight      = 30
  identifier  = "news"
  url         = "/news/"

[[main]]
  name        = "Join Us Today"
  weight      = 40
  identifier  = "join"
  url         = "/join/"

[[footer]]
  name = "NSDCF"
  weight = 10
  identifier = "nsdcf"
  url = "https://nsdcf.org"
  [footer.params]
    external = true

[[footer]]
  name = "Norwin School District"
  weight = 30
  identifier = "norwin"
  url = "https://norwinsd.org"
  [footer.params]
    external = true
