# Development env config
disableAliases = false

[module]
replacements = 'github.com/nsdcf/nsdcf-shared-content -> /Users/tom/code/nsdcf-shared-content/,github.com/nsdcf/nsdcf-theme -> /Users/tom/code/nsdcf-theme/'
